syntax = "proto3";

option java_multiple_files = true;
option java_package = "com.capstone.monitoring";
option java_outer_classname = "MonitoringProto";

package monitoring;

service MonitoringService {
  rpc SendMetrics (MetricRequest) returns (MetricResponse);
}

message MetricRequest {
  string agent_id = 1;          // 닉네임
  double cpu_usage = 2;         // CPU
  double memory_usage = 3;      // RAM

  double disk_usage = 4;        // 디스크
  double net_download_speed = 5; // 다운로드
  double net_upload_speed = 6;   // 업로드
  double network_latency = 7;   // 지연시간

  bool is_java_alive = 8;       // 자바 서버
  bool is_mysql_alive = 9;      // MySQL DB
}

message MetricResponse {
  bool success = 1;
  string message = 2;
}