# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: monitoring.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'monitoring.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10monitoring.proto\x12\nmonitoring\"\xdc\x01\n\rMetricRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x11\n\tcpu_usage\x18\x02 \x01(\x01\x12\x14\n\x0cmemory_usage\x18\x03 \x01(\x01\x12\x12\n\ndisk_usage\x18\x04 \x01(\x01\x12\x1a\n\x12net_download_speed\x18\x05 \x01(\x01\x12\x18\n\x10net_upload_speed\x18\x06 \x01(\x01\x12\x17\n\x0fnetwork_latency\x18\x07 \x01(\x01\x12\x15\n\ris_java_alive\x18\x08 \x01(\x08\x12\x16\n\x0eis_mysql_alive\x18\t \x01(\x08\"2\n\x0eMetricResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2Y\n\x11MonitoringService\x12\x44\n\x0bSendMetrics\x12\x19.monitoring.MetricRequest\x1a\x1a.monitoring.MetricResponseB,\n\x17\x63om.capstone.monitoringB\x0fMonitoringProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'monitoring_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\027com.capstone.monitoringB\017MonitoringProtoP\001'
  _globals['_METRICREQUEST']._serialized_start=33
  _globals['_METRICREQUEST']._serialized_end=253
  _globals['_METRICRESPONSE']._serialized_start=255
  _globals['_METRICRESPONSE']._serialized_end=305
  _globals['_MONITORINGSERVICE']._serialized_start=307
  _globals['_MONITORINGSERVICE']._serialized_end=396
# @@protoc_insertion_point(module_scope)
