plugins {
    id 'java'
    id 'org.springframework.boot' version '3.2.3'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'com.google.protobuf' version '0.9.4'
}

group = 'com.capstone'
version = '0.0.1-SNAPSHOT'

java {
    sourceCompatibility = '17'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'io.grpc:grpc-netty-shaded:1.61.1'
    implementation 'io.grpc:grpc-protobuf:1.61.1'
    implementation 'io.grpc:grpc-stub:1.61.1'
    implementation 'javax.annotation:javax.annotation-api:1.3.2'
    implementation 'net.devh:grpc-server-spring-boot-starter:2.15.0.RELEASE'

    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    runtimeOnly 'mysql:mysql-connector-java:8.0.33'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:3.25.1:windows-x86_64@exe"
    }
    plugins {
        grpc {
            path = "tools/protoc-gen-grpc-java.exe"
        }
    }
    generateProtoTasks {
        all()*.plugins {
            grpc {}
        }
    }
}

def reactAppDir = "$projectDir/../../web-dashboard"

task installReact(type: Exec) {
    workingDir reactAppDir
    if (System.getProperty('os.name').toLowerCase(Locale.ROOT).contains('windows')) {
        commandLine "npm.cmd", "install"
    } else {
        commandLine "npm", "install"
    }
}

task buildReact(type: Exec) {
    dependsOn installReact
    workingDir reactAppDir
    if (System.getProperty('os.name').toLowerCase(Locale.ROOT).contains('windows')) {
        commandLine "npm.cmd", "run", "build"
    } else {
        commandLine "npm", "run", "build"
    }
}

task copyReactBuildFiles(type: Copy) {
    dependsOn buildReact
    from "$reactAppDir/build"
    into "$projectDir/src/main/resources/static"
}

processResources.dependsOn copyReactBuildFiles